### ISSUE TITLE
Use async socket?

### ISSUE THREAD

**Issue by nico159** [Olivine-Labs/Alchemy-Websockets#1]
Why Alchemy don't use async socket directly instead of TcpListener?

And why make an infinite loop on RunClient? It's not better use a Timer to check if the websocket is alive?

**Comment by DorianGray** [comment]
RunClient uses a semaphore in an infinite loop to check(the semaphore blocks, much like a timer), It allows us to have multiple threads listening for clients at the same time and it's a little more responsive than a timer so new data can be received immediately after the old data is done being received.

There is no reason between tcplistener and async socket. There's no real difference even if you were to swap them out.

**Comment by nico159** [comment]
I have a little chat server, it uses async socket and a separate thread for checking if all clients are alive/last heartbeat time
It uses 20 threads (the default ThreadPool I think) for 450 concurrent connections
When we added the websocket layer on it (thank you for your work, your code it's beautiful) with about 750 users connected from the websocket layer Windows now says that my server has more than 300 threads

It's not possible use only one thread for checking connections and leave Windows tell to the websocket server when a socket have a new data?

-I closed this ticket for error-

**Comment by DorianGray** [comment]
You can limit how many threads alchemy will use by setting max/min in the threadpool variable. Alchemy uses a threadpool to do work and apparently your system thinks that it will run most efficiently with that many threads.

Also, those aren't "real" threads, they're IOCP. They use much less memory than full threads.

Thank you for the compliment btw =) Beautiful code is what we strive for =)

**Comment by DorianGray** [comment]
Oh yeah, Alchemy has heartbeat built in =)

**Comment by nico159** [comment]
Ok, thank you

I made a little donation ;-)

**Comment by merarischroeder** [comment]
"those aren't "real" threads, they're IOCP"

So they _are_ asynchronous sockets then! 

On the main website (http://alchemywebsockets.net/), there's no reference to asynchronous sockets. Only calling them "threads" to most people is bad. Given programmers are using this why not use the industry standard terminology "Asynchronous C# WebSocket server for .NET projects"?

I looked for other solutions first, because I was put off by "threads" initially.
