### ISSUE TITLE
hybi 10 does not connect with same ip

### ISSUE THREAD

**Issue by ahsangee88** [Olivine-Labs/Alchemy-Websockets#10]
I have run into a strange issue.  If i am running the client and server on the same IP then it doesn't connects with Hybi 10 protocol. Say for example my client is running on "http://192.168.0.123/test.html" and server is also running on the same IP i.e. 192.168.0.123:8181  then it wont connect with Hybi 10 protocol. Make sure to call the server like "ws://192.168.0.123:8181/websockets".

Has anyone else faced this issue? i have tested this on latest versions of chrome and safari. Both have same issue. Whereas older versions of these browsers work fine, because they are implementing 76 version of the protocol.

**Comment by ajacksified** [comment]
We've fixed connecting to the same IP; there was an issue where origin was not being set if testing locally.

**Comment by ahsangee88** [comment]
thanks for the fix.
