### ISSUE TITLE
UserSocket Connect not behaving like expected

### ISSUE THREAD

**Issue by ShyRed** [Olivine-Labs/Alchemy-Websockets#11]
The server side `UserContext` Connect delegate does not behave like one might expect...

**What I expect:**
The Connect delegate is called once the connection establishing and handshake are complete, so I can greet every newly connected user with a "welcome message" inside the Connect delegate.

**What happens:**
The Connect delegate is called before the handshake which causes errors / disconnects, if one messages the client inside the Connect delegate.

**Workaround:**
Right now you have to poll the `UserContext.IsSetup` property in order to find out when a client is ready for receiving custom messages.

**Solution:**
1) Call the Connect delegate after the handshake.
_OR_
2) Split the delegate into 2 separate delegates: Connecting (is called before handshake) and Connected (is called after handshake).

**Comment by ajacksified** [comment]
Added "Connected" event as well (https://github.com/Olivine-Labs/Alchemy-Websockets/commit/b9a217e6d3601d1c79a2ecdb86d4a0035466fdcb)
