### ISSUE TITLE
New DLL ? 

### ISSUE THREAD

**Issue by fairport** [Olivine-Labs/Alchemy-Websockets#12]
Hi 

Background
We've been developing an offline application that will (when released) be running on mobile devices. We chose alchemy for our websocket setup.  Now using it for 6 months... Our use involves data syncronization using JSON between an SQL Server DB and SQLite DB on the mobile devices.

At the moment we have trouble with Chrome & Chrome canary - we can connect to the server, but long messages are not receiving or sending.
... but Safari is working fine. 100% 
We don't believe this is an Alchemy problem, but in case it is, can you please compile a new dll with the latest round of bug fixes and make it available. 

Thanks
Roger

**Comment by ShyRed** [comment]
Hi fairport,

the issue with sending / receiving long messages is a known bug which has not been fixed yet.

Palomo Valdes and silentbluedev are working on it as far as I can tell ( see https://github.com/Olivine-Labs/Alchemy-Websockets/pull/8 ).

PS:
You can get the most current version / DLL very easily by downloading the project via https://github.com/Olivine-Labs/Alchemy-Websockets/zipball/master and compiling it yourself using Visual Studio 2010.

**Comment by fairport** [comment]
Hi There

Thanks

We have compiled the latest set of code updates and we are back in business! Thanks Again

Regards
Roger Wiese 
Fairport Farm Software | Fairport Technologies | FTI (1997) Pty Ltd
.................................................................................

-----Original Message-----

**Comment by ajacksified** [comment]
Good to hear; we've also pushed some updates that fix compatibility with Chrome canary builds, which use a newer version of the protocol.
