### ISSUE TITLE
Masked Response Error - Using Web-Socket-Js

### ISSUE THREAD

**Issue by iRubens** [Olivine-Labs/Alchemy-Websockets#14]
I'm using Alchemy with Web-Socket-Js (to support other browsers).
The first days everything worked well, but now, for browsers using websockets through flash i get this error in console:

> [WebSocket] Fail connection by client: code=1002 reason=Frame from server must not be masked.

followed by the closing of the connection.

Investigating into [Web-Socket-Js](https://github.com/gimite/web-socket-js) i find [this](https://github.com/gimite/web-socket-js/issues/103) issue. They updated the project in order to close connection, with masked response.

Alchemy recognizes the protocol as 'hybi10'...

It is right? Someone has an idea wheres the problem and how to solve it?

Thanks, i'll investigate the problem too.

**Comment by ajacksified** [comment]
We're taking a look at flash socket support now; we should have an update fairly soon.

**Comment by ajacksified** [comment]
There was a problem with an earlier version of web-socket-js that is now fixed.
