### ISSUE TITLE
hybi00 DataFrame: Payload loses data in Append()

### ISSUE THREAD

**Issue by davidcchase** [Olivine-Labs/Alchemy-Websockets#16]
I've got a simple test server running with Alchemy. I can pass data back and forth with Chrome (hybi10) but not with Safari (latest version, w/ hybi00).

Safari connects fine, but when I send data over the socket (Safari to server), it's not in the UserContext by the time it gets to my OnReceive handler.

In the debugger, I've tracked it enough to see the the data come in and get added to the Payload in hybi00.DataFrame.Append, but it "disappears" (Payload count goes from 1 to 0) when I step out of the "if (data.Length > 0)" block...usually. I won't go into all the hoops I've jumped trying to diagnose it; suffice it to say it's one of those "impossible" behaviors that usually ends up being some absolutely obvious oversight (on my part), but I'm stumped.

**Comment by DorianGray** [comment]
Hey, thanks for the report on this one! Noticed you had to register for github and everything just to get this across.

I fixed it in latest(forgot to test hybi00 data transfer). It was a problem where the header and footer(1 byte each) weren't getting added to the payload before getting converted to raw data, so the raw data was getting removed instead!

Give it a shot now!

**Comment by davidcchase** [comment]
Thanks! Safari-to-server now works. However data sent to Safari doesn't get there (the client-side event handler isn't triggered). I'll put this into another issue.
