### ISSUE TITLE
onmessage event handler isn't fired in Safari

### ISSUE THREAD

**Issue by davidcchase** [Olivine-Labs/Alchemy-Websockets#17]
Running Safari 5.1.2 and Alchemy commit 91740178b5 (12/21/11).

With a very simple websocket server, call UserContext.Send(string) with a live connection. The browser-side function assigned to WebSocket.onmessage gets triggered with the correct data in Chrome but does not get triggered at all in Safari.

Also tried it using the Alchemy javascript client library, same deal: Alchemy.MessageReceived doesn't get called in Safari.

Running the server in the debugger, I can't see the problem. BeginSend is called on an open TcpClient connection socket in Handler.Send and there's no error. Maybe the data format is incorrect for hybi00, as in the recent OnReceive problem?

Thanks, Dave

**Comment by DorianGray** [comment]
Thanks for the report! We're working on this and should have a fix momentarily

**Comment by DorianGray** [comment]
Alright, got it fixed as of latest commit. I derped and forgot to initialize the start and end bytes in the AsFrame function in DataFrame. It's all good to go now! I just tested using our chat demo application and was able to chat between a chrome and a safari client with no problems(one hybi10 and the other a hybi00 protocol).

**Comment by davidcchase** [comment]
Thank you thank you thank you! What an excellent x-mas present. Happy Holidays!
