### ISSUE TITLE
OnReceive after OnDisconnect

### ISSUE THREAD

**Issue by dustingraham** [Olivine-Labs/Alchemy-Websockets#19]
I'm not sure if I'm using this incorrectly, but I'm a bit confused about the timeout and OnDisconnect.

I've got a client/server working pretty well. But, after the timeout (I used the example of 5 minutes) it fires OnDisconnect, but it doesn't close the connection. Then, if the client sends a message, OnReceive fires.

The reason this is a problem in my case is because I remove the "client" from known clients assuming they'll reconnect later. However, then on OnReceive I can't find the context because I removed it from my known client list.

Am I doing something wrong, or am I supposed to forcefully close the connection some how on the timeout's OnDisconnect call?

Or, is this a bug of some sort, leaving the open connection? Could it be that I have a reference somewhere which isn't GC'd and the socket only closes on dispose? Although I do store a reference in my own "Connection" class, on disconnect I set this.Context = null;

Thanks for any thoughts.

(Is there a way to contact you directly?)

**Comment by dustingraham** [comment]
1) I meant my "connection" class stores an instance to UserContext, which I set to null OnDisconnect.

2) Just thinking -- maybe I should extend UserContext and OnDisconnect call _context.Connection.Client.Disconnect() or Close().

Edit\* P.S. Love the library thanks for putting this together.

**Comment by ajacksified** [comment]
The client is supposed to adhere to the OnDisconnect call; it appears that your specific client is failing to actually fire the disconnect. What are you testing with?

**Comment by dustingraham** [comment]
Ahh, it's okay, we can close this. I had to move to a different project. I was using Google Chrome with the alchemy.js client javascript library. The time I noticed this happen was after a period of idle. My C# debugger would be break-pointed on the "OnDisconnect" call and it would trigger, then when I send a message again from the client, it would trigger OnReceive.

Seems odd that OnDisconnect would fire when the socket isn't actually disconnected and closed.

**Comment by dustingraham** [comment]
Ahh, I found my problem. I had a timeout set for 5 minutes. It looks like if the timeout is hit, it disconnects the C# alchemy socket, but the web client thinks it is still connected. My solution is to change the timeout to 10 minutes, and after 5 minutes do a warning for the user that the socket will close, then force the close at 6 minutes.

Edit: I wonder if alchemy should send a "close" message when the timeout is hit?

(Line 136 & Line 150 of WebSocketServer.cs)
