### ISSUE TITLE
hybi10 support?

### ISSUE THREAD

**Issue by torjue** [Olivine-Labs/Alchemy-Websockets#2]
Can't seem to get it working with the latest chrome dev (14.0.835.18). I guess it's because of the switch to the hybi10 spec.

**Comment by DorianGray** [comment]
Yeah, once we get a little time I'll update it. It shouldn't take but about an hour or so to dev and test it. Plan on late september/early october.

**Comment by beaugunderson** [comment]
Hey torjue; I spent today adding hybi10 support (what a way to learn the websocket spec, I had to wrap my head around C# BitArrays).

I forked the repo and I'll put my changes there within a day or two.

**Comment by DorianGray** [comment]
I just got some time today and implemented hybi10 in alchemy. Actually used it as an excuse to put some other work off, lol.

I tested it in our chat server demo, I should have that updated with the new dll shortly as well.

**Comment by beaugunderson** [comment]
Hey Hardt; you just implemented the handshake and authentication portions, correct? To support Chrome 15's HyBi 10 websockets I think you'll still need to support the new framing protocol (my fork contains an implementation, though it's not perfect yet as it doesn't handle fragmented frames)

**Comment by torjue** [comment]
iOS/Safari uses hixie76, and firefox 6 uses hybi07. Beaugundersons branch will support hybi-07 in addition to hybi-08/10, as far as I can see.

I think it is important to keep hixie76 support in addition to hybi-07/08 (because of iOS) so I've started the work to get Alchemy to support both hixie76 and hybi07+.

My plan is to check the request header and set the appropriate handler (say WebSocketHybi10Handler.cs / WebSocketHixie76Handler.cs). Look out for a possible pull request. If I get it working, that is.

**Comment by DorianGray** [comment]
I went ahead and implemented the new framing including fragmented frames although my chat test app keeps sending a close frame immediately along with the data, not sure why yet.

Torjue - that is a good idea. I hadn't thought of people who don't update iOS ever. It would be very easy to check the version in the header and switch between the old versions of websocketauth and the new ones. If you don't end up doing it within the next week or so I will.

**Comment by DorianGray** [comment]
Just fixed hybi10 support and implemented hybi00 alongside it. Both are supported in the multi-protocol branch. hybi00 needs some testing and debugging apparently(which also doesn't make sense since I just copied the old versions of the files).
