### ISSUE TITLE
Received illegal masked frame, using AS3WebSocket library

### ISSUE THREAD

**Issue by mantolo** [Olivine-Labs/Alchemy-Websockets#21]
hi,
I am now using AS3Websocket ( https://github.com/Worlize/AS3WebSocket ) to write an AIR web-socket client application, and using  application written in C# with Alchemy as server.

when I connect client to websocket.org echo test server( http://www.websocket.org/echo.html ), I can send and receive data perfectly;
when client connect to my server, client sends and server receives; but when server sends and client receives, the client shows error code 1002, said received illegal masked frame from server.

Having a quick look about the error code according to the specification of RFC6455 (http://tools.ietf.org/html/rfc6455#section-5.1)
"A server MUST NOT mask any frames that it sends to the client.". 
Hence, I guess there is something wrong about the protocol between the client and server.

I would kindly ask  for your support on this issue, any help would be great :)

**Comment by ajacksified** [comment]
Thanks- I'll check this out and see what I can confirm.

**Comment by ajacksified** [comment]
Confirmed that it's masking when it shouldn't; our implementation of client and server are coupled, so we'll have to do some refactoring to get this working. We're on it, though!

**Comment by jrperina** [comment]
+1 seems to be showing up with the latest version of Chrome (version 19).

**Comment by mantolo** [comment]
Thanks for the reply. It is good to hear that you're getting to fix this issue,
looking forward to see new batch soon!

**Comment by 0xStuart** [comment]
+1 here.  If anyone knows of a quick fix, please contact me. All of a sudden I'm getting bombarded with Chrome folk with this problem. :(

**Comment by ajacksified** [comment]
@stuorguk you could try to use https://github.com/gimite/web-socket-js and set `window.WEB_SOCKET_FORCE_FLASH = true`; I'll be trying to fix this particular issue tonight

**Comment by 0xStuart** [comment]
Thanks.  I dont actually use the client code.  Just the server side.  I'm just trying to get my head around the masking to see if it's something I can disable quickly.

**Comment by mantolo** [comment]
Actually I have drilled-down abit to see what was happening in my case.
By comparing data being sent & received, I have found that the message dispatched from server side does not contain header bytes, which should be presented in web-socket frames to describe what data it is.
So if you are looking for a quick fix, you could try to manually create and attach header bytes in your code before you send message.

refer to http://tools.ietf.org/html/rfc6455#section-5.2 for header bytes structure

**Comment by 0xStuart** [comment]
My code has been hacked about quite a bit, but the header bytes are there from my server. Removing the masking is actually easy. Remove the mask bit, and comment out the mask method call.  Seem to have a problem with UTF-8 decoding now... investigating.

**Comment by 0xStuart** [comment]
Mine is working now.  As above, I just commented out the masking code where it builds a packet.  I forgot to take out the mask key from the header which caused UTF-8 errors.

**Comment by jrperina** [comment]
Stuorguk, can you be a little more specific about what you did? I started commenting out the masking code as well, but now I'm getting unexpected characters encountered issues.

**Comment by jrperina** [comment]
I got mine working now too. Just a couple specifics: 

In the Hybi10 implementation I commented out the following lines: 

In DataFrame.AsFrame():

Mask(); //Uses _header, must call ToBytes before calling Mask

In FrameHeader.ToBytes():

data[0] = (byte) (data[0] | 0x80); //Tells us that this data is masked

data[0] = (byte) (data[0] | 0x80); //Tells us that this data is masked

data[0] = (byte) (data[0] | 0x80); //Tells us that this data is masked

Mask = random.Next(Int32.MaxValue);
headerBytes.Add(BitConverter.GetBytes(Mask));

I test it with both the Flash Socket and against Chrome 19 and it seems ok now. Haven't tested yet against older versions of Chrome.

**Comment by ajacksified** [comment]
Thanks; I can put in an emergency fix for now and work on updating the
client later. It gets tricky in that the WebSocket client uses the same
dataframe class, but it may be as simple as passing in a parameter when
creating the data frame to tell it when to mask. This kills the integration
tests.

Does anyone use the client? Would it be a problem to break it for a day or
two, to get the server running?

On Fri, May 18, 2012 at 11:07 AM, jrperina <
reply@reply.github.com

**Comment by coldwired** [comment]
Hi,

I'm experiencing this issue too. jrperina's quick fix works for Chrome but it doesn't work with Safari or an iOS emulator. Has a patch been released for this issue yet?

Thanks,
Colin.

**Comment by ajacksified** [comment]
Appears to work and passes all of my tests; used @jrperina fix.

**Comment by ajacksified** [comment]
@coldwired Safari and iOS use an old version of the websocket protocol that we haven't built in support for yet; we'll re-open that now that we've moved past this chrome issue.
