### ISSUE TITLE
Converter error

### ISSUE THREAD

**Issue by pipothebit** [Olivine-Labs/Alchemy-Websockets#22]
Hi,
Sorry about my english!

In file FrameHeader.cs I have found a little conversion error. On line 84:

data = BitConverter.GetBytes(Convert.ToInt16(PayloadSize));

I have got exception on message length of 65500 bytes so I have changet that line to:

data = BitConverter.GetBytes(Convert.ToUInt16(PayloadSize));

By the moment works fine.

Byeer! :)

**Comment by ajacksified** [comment]
Thanks. If you send in a pull request, we can verify; otherwise we'll work on testing this ourselves and get it in sometime soon.

**Comment by ajacksified** [comment]
Updated. Thanks!
