### ISSUE TITLE
Possible version detection problem

### ISSUE THREAD

**Issue by akurdyukov** [Olivine-Labs/Alchemy-Websockets#23]
I'm testing Alchemy Websockets in Chrome 17.0.963.56 on Mac. Currently I have problems with client to server message sending. My client sends message like

```
{"Type":"Auth","Msg":{"SessionId":"test1"}}
```

But server OnReceive handler gets

```
ABw8UmFuZG9tQnl0ZXM%2ba19fQmFja2luZ0ZpZWxkHDxDcmVhdGVkRGF0ZT5rX19
```

The other strange thing is that HTTP Upgrade request have headers

```
Sec-WebSocket-Key:DzPxIMY4zgU+jUcfVIO+ZQ==
Sec-WebSocket-Version:13
Upgrade:websocket
```

But server thinks that protocol is Hybi10. Is this correct?

PS. Test project source is https://github.com/akurdyukov/NancySelfHost

**Comment by ajacksified** [comment]
10 and 13 are close enough that the server can safely handle them both; I'll take a look at your example source and see what we can confirm. Thanks!

**Comment by ajacksified** [comment]
Everything looks right; I'm able to run Alchemy with Chrome 17 on Mac (my main dev box is OSX.) Try with the latest Alchemy, perhaps?

I'm having some trouble running your demo code; I tried connecting and sending to a socket with console output.

**Comment by ajacksified** [comment]
Can't reproduce, no further details given; going to close. Re-open if you have any more details or are still experiencing the problem.
