### ISSUE TITLE
Issue with Chrome ver 19.0.1084.52 m

### ISSUE THREAD

**Issue by KGAP** [Olivine-Labs/Alchemy-Websockets#26]
I've been using the WebSockets library on my test server since about a month. A few days ago it stopped working. On investigating , I found the following error message: "A server must not mask any frames that it sends to the client."
I think this happened after the Google Chrome browser was updated to version 19.0.1084.52 m.

**Comment by ajacksified** [comment]
Duplicate of issue #21 - also, fixed.

**Comment by KGAP** [comment]
Thanks. Is working fine now.

-----Original Message-----
