### ISSUE TITLE
Server OnDisconnect event fired without OnConnect

### ISSUE THREAD

**Issue by evgeniyp** [Olivine-Labs/Alchemy-Websockets#27]
In your example code interrupting client OnConnect event with exception:
http://pastebin.com/309vFCUK
causes server code crash
http://pastebin.com/SxHy0w3c

Is it normal when server OnDisconnect event fired without OnConnect?

**Comment by ajacksified** [comment]
Given the code, your OnConnect didn't add anything to the dictionary - so it makes sense that it would throw an exception in the user OnDisconnect. You have to write safe code on your server.
