### ISSUE TITLE
Issues with larger messages

### ISSUE THREAD

**Issue by cbargren** [Olivine-Labs/Alchemy-Websockets#3]
Hey guys. I wanted to say that I think this project is pretty awesome. I was doing some experimenting with WebSockets and was very disappointed with the HTML5Labs' .net server implementation because of it's blatant lack of support for all previous versions of the protocol before the most recent hybi10 spec. Your implementation is pretty well-rounded, though and I've been pretty happy with what I've seen. :) That being said, I ran into an issue when I was playing around with the example and I was wondering if you could shed some light on it. I'm running the server locally and it seems to work fine when I navigate to the example webpage. I can type short messages and see them just fine in the chat window across multiple instances of the client. However, when I type somewhat large messages in the chat window (I've observed the issue beginning at about 84 characters), the server fails to broadcast the message to the other clients (Note that I debugged the program and I saw that the server is actually receiving the message and does get to the u.Context.Send(message); line but the clients just don't seem to receive the message sent). Is this a configuration error on my part or am I missing something? I'm using dev channel Chrome (v15.0.874.5), which implements the hybi10 spec of WebSockets, right now to test it. Thanks!

**Comment by 0xStuart** [comment]
Its an endian problem.  The code assumes its running on a little-endian cpu (x86), but although I cant see any reference to it in the websockets spec, the protocol is big-endian.

The bytes need to be reversed like this in the Wrap method:

```
               if (Data.Length <= ushort.MaxValue)
                {
                    HeaderBytes[1] = 126;
                    byte[] len16 = BitConverter.GetBytes((UInt16)Data.Length);
                    HeaderBytes[2] = len16[1];
                    HeaderBytes[3] = len16[0];
                    StartIndex = 4;
                }
                else
                {
                    HeaderBytes[1] = 127;
                    byte[] len64 = BitConverter.GetBytes((UInt16)Data.Length);
                    Array.Reverse(len64);
                    Array.Copy(len64, 0, HeaderBytes, StartIndex, 8);
                    StartIndex = 10;
                }
```

and in the Append Method:

```
            if (DataLength == 126)
            {
                Array.Reverse(Data, StartIndex, 2);
                DataLength = BitConverter.ToInt16(Data, StartIndex);
                StartIndex = 4;
            }
            else if (DataLength == 127)
            {
                Array.Reverse(Data, StartIndex, 8);
                DataLength =BitConverter.ToInt64(Data, StartIndex);
                StartIndex = 10;
            }
```

To make it work on all architectures, use BitConverter.IsLittleEndian

**Comment by ajacksified** [comment]
Sorry for the delayed response - we're aware of this issue and should have it fixed shortly in the main repo. If you have a fix before us, feel free to fork it and do a pull request.
