### ISSUE TITLE
WebSocketClient Path Param

### ISSUE THREAD

**Issue by Austin-Liang** [Olivine-Labs/Alchemy-Websockets#32]
I use it like this:

var aClient = new WebSocketClient("ws://172.28.1.103:8100");

but got a FormatException Error.

the documentation here : 
http://alchemywebsockets.net/docs/class_alchemy_1_1_web_socket_client.html

didn't show any sample code.

so, could anyone gives me some help here?

TKS.

**Comment by ajacksified** [comment]
Closed over email - needs a path like "ws://172.28.1.103:8100/chat" or "ws://172.28.1.103:8100/socket".
