### ISSUE TITLE
Incorrect byte[] handling

### ISSUE THREAD

**Issue by prakashrx** [Olivine-Labs/Alchemy-Websockets#34]
I noticed 3 issues when developing a test server application. I also found the bugs within and I am sharing it with you. If you find it relevent please update your code. And thanks for providing this wonderful library.

When the websocket client send a large byte[], say > 1024 bytes, data to the server, there is some data corruption happening. What I send is not what I receive.

Cause:  Hybi10 DataFrame::Append method incorrectly handles incoming data, There are 2 issues within it.
Solution:

Issue 1:
Original Code:

```
                   data = new byte[ Math.Min(Convert.ToInt32(Math.Min(_header.PayloadSizeRemaining, int.MaxValue)),
                                 someBytes.Length)];
```

Ideally, we need to subtract headerBytes.Length from someBytes.Length, since we already removed the header part. If this is not done, then there would be a 4 byte hole within our first segment.

Fix:

```
                   data = new byte[ Math.Min(Convert.ToInt32(Math.Min(_header.PayloadSizeRemaining, int.MaxValue)),
                                 someBytes.Length - headerBytes.Length)];
```

Issue 2:
Original Code:

```
             else
            {
                dataLength = Math.Min(Convert.ToUInt64(data.Length), _header.PayloadSizeRemaining);
                if (dataLength < Convert.ToUInt64(data.Length))
                {
                    data = new byte[dataLength];
                    Array.Copy(someBytes, 0, data, 0, Convert.ToInt32(dataLength));
                }
            }
```

When the dataLength is equal to 512 bytes, the current code would not copy the incoming byte[]  into the new buffer, instead, this would set the reference of original byte[] as data. This is incorrect, because when the next packet arrives via socket, this data gets modified, and we would end up corrupting the earlier data.

Fix:

```
            else
            {
                 //Always copy
                dataLength = Math.Min(Convert.ToUInt64(data.Length), _header.PayloadSizeRemaining);
                data = new byte[dataLength];
                Array.Copy(someBytes, 0, data, 0, Convert.ToInt32(dataLength));
            }
```

Issue 3:
When the server send a byte[] back to the client the websocket frame header always sets the Opcode as 1 (which represents Text). One would expect this to be set as Binary( Opcode 2) since we are sending byte[]

Cause: FrameHeader::ToBytes().  

Original Code:

data[0] = 0x81;   //This is harcoded as Text. 

Solution:
If the data is sent as byte[], then we would expect data[0] = 0x82. So there needs to be some distinction between text and binary data.

**Comment by ajacksified** [comment]
fixed - pull request #36
