### ISSUE TITLE
Virus warning for http://olivinelabs.com/

### ISSUE THREAD

**Issue by jdschuitemaker** [Olivine-Labs/Alchemy-Websockets#37]
This is the warning my eset anti virus shows in Firefox when I go to your site:

ESET NOD32 Antivirus
    Access denied

Details:  
Web page:   http://olivinelabs.com
Comment:    Access to the web page was blocked by ESET NOD32 Antivirus. The web page is on the list of websites with potentially dangerous content.

Not sure if this is valid, but you might want to do something about it if this is valid.

**Comment by ajacksified** [comment]
Weird. Definitely not valid, it's a Github Pages page; we've had reports on other pages too that were static html. Thanks.

**Comment by shviller** [comment]
I don't know if it is in any way helpful for you to know, but the exact same thing is happening again.
