### ISSUE TITLE
UserContext class should expose _context as protected instead of private

### ISSUE THREAD

**Issue by Rushino** [Olivine-Labs/Alchemy-Websockets#42]
Hello, i wanted to disconnect an user which is connect to my server but there no method available for this operation. The fix would be the change the _context protection level from the UserContext class to protected so we can inherit from the UserContext class and add our own method which could also enable us for more control _or_ just implement a disconnect method. I want your opinion on that. Is there a reason why the _context is private ?

**Comment by ajacksified** [comment]
Moved to protected - fixed with commit 4d768056a79cde9dce60bdd636d8def293b54985
