### ISSUE TITLE
Connection is still open when i close the server using .Stop()

### ISSUE THREAD

**Issue by Rushino** [Olivine-Labs/Alchemy-Websockets#43]
It seem the connection from the browser is still open when i use .Stop() i have to close the whole server application to make the user to disconnect.

**Comment by BradDodi** [comment]
+1. I'm also having this problem.

**Comment by ssdvn** [comment]
I fixxed this issue.

Solution: Classes\Context.cs method Dispose() :

``` csharp
/// <summary>
/// Performs application-defined tasks associated with freeing, releasing, or resetting unmanaged resources.
/// </summary>
public void Dispose()
{
    Connected = false;
    UserContext.OnDisconnect();

    // close client connection
    if (Connection != null)
    {
        try
        {
            Connection.Close();
        }
        catch (Exception)
        {
            // skip
        }
    }   
}
```

**Comment by ajacksified** [comment]
@ssdvn it would be super awesome if you could open up a pull request (https://help.github.com/articles/using-pull-requests)

**Comment by ssdvn** [comment]
@ajacksified Done.

**Comment by ajacksified** [comment]
@ssdvn thanks!

**Comment by atulyadav** [comment]
@ssdvn thank you very much :+1:
