### ISSUE TITLE
Synchronic Send

### ISSUE THREAD

**Issue by CheloXL** [Olivine-Labs/Alchemy-Websockets#46]
A nice feature to have is the ability to have a synchronic Send method. I understand that the basics of sockets are async communications, but for a specific application I'm working on I found that a sync send method would simplify my life a lot :) I need to send a packet and be sure that the packet is sent before continuing doing things (like sending more -async- packets).

**Comment by DorianGray** [comment]
You can implement this in your application I believe...I don't think it has a place in Alchemy due to the implementation specific nature of the request.
