### ISSUE TITLE
Bug: DataFrame.Wrap() modifies provided byte array

### ISSUE THREAD

**Issue by ShyRed** [Olivine-Labs/Alchemy-Websockets#5]
The `WebSocketHandler.Send()` method passes its given parameter Data byte array to the `DataFrame.Wrap()` method which in turn calls its private method `Mask()` which in turn manipulates the byte array.

As a result, since arrays types are reference types ( see http://msdn.microsoft.com/en-us/library/9b9dty7d.aspx ), the Send() method modifies the original provided byte array. (Note: since arrays are reference types already, the `ref` keyword in the `Mask()` method parameter list is not necessary, if you want to modify the array content only!)

Example for better understanding:

``` c#
          server.DefaultOnReceive = (ctx) =>
          {
            byte[] data = ctx.DataFrame.ToBytes();
            foreach (UserContext context in clients)
              if (context.ClientAddress != ctx.ClientAddress)
                context.Send(data);
          };
```

In the foreach loop the first client will receive a correct message from the server. The second client will receive damaged data, since the previous call to the `Send()` method modified the data-byte array.

**Comment by DorianGray** [comment]
That particular send buffer is overwritten for each send operation and therefore is not corrupted for the next request. This does need refactoring as it is hard to understand.

I forget why I put in "ref" for the mask function but I'll investigate that shortly.

**Comment by DorianGray** [comment]
Oh wait, I see what you're doing. I'll take a look at what I can do to make this a little easier to use.

**Comment by DorianGray** [comment]
Quick workaround until I get this fixed, pass in a string rather than a byte buffer...it will copy your data for each send. Alternatively, copy your array for each iteration.

**Comment by DorianGray** [comment]
Okay, I just committed the fix for it. Take a look and let me know if that solves the problem.
