### ISSUE TITLE
Alchemy performance is horrible with large number of clients

### ISSUE THREAD

**Issue by jhaygood86** [Olivine-Labs/Alchemy-Websockets#52]
Alchemy performance is horrible with large number of clients ( > 1000).

I rewrote large portions of the concurrency control for our local build which was able to handle >10,000 concurrent users on a single Amazon small instance.

Summary of changes:
1. Switch to SocketAsyncEventArgs (2 per context -- 1 for sending, 1 for receiving) and SendAsync/ReceiveAsync versus using Begin/End
2. Use static threads for actual receiving and sending of messages
3. Don't "block" on threadpool threads -- reduces threads from 1 per connection to a few for all several thousand (i.e., return on OnRunClient immediately and let static worker threads do the work)

You can see our diff at: https://gist.github.com/4199234

**Comment by dustingraham** [comment]
Brilliant jhaygood86. Thanks for sharing this. I may not ever scale to need this on my personal project, but I'm glad it's here.

**Comment by jhaygood86** [comment]
It helps even under low load. Do you want me to branch it and provide a pull request, or do you want to integrate the changes yourself?

**Comment by dustingraham** [comment]
@jhaygood86 I'm not the maintainer of this repository. I'm just watching it, and using it in my own projects. You don't need to branch it for my own sake, but Olivine-Labs, and other users may benefit from it.

**Comment by ajacksified** [comment]
@jhaygood86 Thanks for linking the patch; I'll check it out!

**Comment by ajacksified** [comment]
Merged pull request #55 - closing this. Thanks everyone!
