### ISSUE TITLE
WebSocketServer weird connection behavior

### ISSUE THREAD

**Issue by ilmax** [Olivine-Labs/Alchemy-Websockets#57]
Hi, i'm experiencing following issue:
When a client try to connect to the server, the server fires the OnConnect delegate, and the immediatly the OnDisconnect, but If i put a break-point in the OnConnect server delegate everything was fine.

Scenario:
Server -> Asp.Net solution hosted by IIS Express (the default version installed with VS2012)
Client -> Console App.

After spending some time to look around over the internet i decided to download the code and try to debug for better investigate my problem and following is what i see.

if the client send the GET  HTTP/1.1 request after the 
context.Connection.Client.BeginReceive(context.Buffer, 0, context.Buffer.Length,
                                                                   SocketFlags.None, DoReceive, context);
of WebSocketServer, the server call the Alchemy.Handlers.Handler to handle the request, the handler read the data and set the context.Header = new Header(data); and then changes the context.Handler according to the context.Header.Protocol, the newly handler try to authenticate (remeber that current request is only GET  HTTP/1.1) but authentication fail and OnDisconnected will be fired, now the client send a 

Host: localhost
Origin: localhost
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: 3fIK+fw0rUAhXOG/rmmdCw==
Sec-WebSocket-Protocol: 
Sec-WebSocket-Version: 8

the server start handling the request with the handler that is an instance of Alchemy.Handlers.WebSocket.hybi00.Handler, the handler now checks the authentication again but context.Header is still empty (No one has set the Header) so the authentication will fail another time.

If i set the breakpoint in the OnConnect method on the server (or wait some time in some manner e.g. Thread.Sleep), the server receive a unique request from client like following:

GET  HTTP/1.1
Host: localhost
Origin: localhost
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: R12sHIncOITnKiKCbR2N0g==
Sec-WebSocket-Protocol: 
Sec-WebSocket-Version: 8

And the authentication goes fine.
If it can be usefull, i have a solution to reproduce this behavior.

**Comment by jhaygood86** [comment]
Do you still have this problem with current git version? BeginReceive is no longer used.

**Comment by ilmax** [comment]
Now (with latest changes) the server work just good, i'm experiencing an issue on the client side, but i will investigate further and eventually open another issue.

Bests Max.
