### ISSUE TITLE
Forgotten Console.Write in DataFrame?

### ISSUE THREAD

**Issue by ShyRed** [Olivine-Labs/Alchemy-Websockets#6]
In `Alchemy.Server.Handlers.WebSocket.hybi10.DataFrame` there is the following line inside the `Wrap()` method:

``` C#
Console.WriteLine(Encoding.UTF8.GetString(WrappedBytes));
```

It seems that someone forgot to remove their debugging code? ;-)

PS:
Reporting this, since that line spams my Console Window which slows down and sometimes even crashes my console window server application...

**Comment by DorianGray** [comment]
Wow, I apologize. That was totally my fault. I just pushed a fix for that, as well as a ton of code cleanup and refactoring. Hopefully by the end of today I'll have several more issues fixed as well as several performance improvements and memory optimizations.
