### ISSUE TITLE
Flashsocket no longer receiving Connected()

### ISSUE THREAD

**Issue by ShyRed** [Olivine-Labs/Alchemy-Websockets#7]
Hi there,

after upgrading to the latest version from git, browsers using the flashsocket fallback will not trigger the JavaScript `Connected()` callback anymore.

They do establish a connection (I see that on my server) and they also get the `Disconnected()` when the server goes down, but they never get to the `Connected()` ...

Except for upgrading the server, I did not change anything client side.

Is anyone else having the same issue / can verify this?

**EDIT:**
I was able to verify the issue myself. After downgrading to version https://github.com/Olivine-Labs/Alchemy-Websockets/tree/1d73aeaee855a63fb9a94640e67f739705ca10c4 the problem is gone and the flashsocket fires the `Connected()` ...

**Comment by ajacksified** [comment]
Was a problem with earlier flash socket library; latest version of flash socket library works properly.
