### ISSUE TITLE
Does not work with iOS and Android

### ISSUE THREAD

**Issue by ChristianWeyer** [Olivine-Labs/Alchemy-Websockets#9]
I cannot figure out what to do to get Alchemy working with iOS and/or Android.
My app runs fine in Chrome on Windows.

E.g.: http://liveperfmon.cloudapp.net/

Thanks!

**Comment by ChristianWeyer** [comment]
Also problems when using desktop Safari...

**Comment by ChristianWeyer** [comment]
this is what is being sent by iOS:

GET /perfdata HTTP/1.1\r\nUpgrade: WebSocket\r\nConnection: Upgrade\r\nHost: 192.168.178.23:88\r\nOrigin: http://192.168.178.23\r\nSec-WebSocket-Key1: 3@ ]N  5  210Nz 27  52 ^\r\nSec-WebSocket-Key2: 3\ 7 319 8 6(9     j4`  0\r\n\r\nE5?O$

and this from Chrome (desktop):

GET /perfdata HTTP/1.1\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nHost: localhost:88\r\nSec-WebSocket-Origin: http://127.0.0.1:81\r\nSec-WebSocket-Key: WhWlKfd9/HLKVVlnhtaVcA==\r\nSec-WebSocket-Version: 8\r\nCookie: ASP.NET_SessionId=hvpmfimy3yz3xpetjmvyi5y0; name=CW\r\n\r\n

... if it is of any help ;)

**Comment by ajacksified** [comment]
Christian,

Android doesn't support websockets (and as far as I know it isn't planned for Version 4.0 either. Sadface. ) You could use a flash shim on the client for users who have flash installed, but that's the only way you'll get websockets. iOS has websockets, but they use hixie-76, an older protocol; we do support hixie-76 with our latest update, but we haven't tested it on iOS so there may be something weird going on. Check the website http://websocket.org/echo.html on the devices you're testing to check for websocket feature availability.

I've been able to connect client-side; can you put the code you're trying to connect to the webserver with in jsfiddle or pastebin or something?

**Comment by ChristianWeyer** [comment]
Sure :)
http://pastebin.com/1AMvgvWB

**Comment by ajacksified** [comment]
@christianweyer, try ws:// rather an wss:// and see if you have any more luck. Perhaps there's an issue with the secure connection implementation.

**Comment by ChristianWeyer** [comment]
Nope, the same.

**Comment by ajacksified** [comment]
We've pushed some updates; I don't have an iOS device to test with, if you wouldn't mind giving it a shot again. Thanks!

**Comment by ajacksified** [comment]
Fixed for Android (which uses the flash socket); iOS uses a super old version of websockets that we don't support (hixie-75)
