### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by jgillich** [Olivine-Labs/Alchemy-Websockets#90]
I am a bit confused about the licensing of this project. When you say "LGPL and MIT", I assume that terms of the LGPL and the MIT **both** apply at the same time.

However, the website states the opposite:

> Licensed under LGPL and MIT. This makes it compatible with GPL licensing and allows you to use Alchemy in both commercial and open-source projects with no limitations or liabilities.

My interpretation of this is that I could choose **one** of the two licenses.

Could the copyright holders please clarify?

**Comment by ajacksified** [comment]
You can choose either. Sorry for the confusion! I'll update the license file.
