### ISSUE TITLE
What is trigging point for C# 

### ISSUE THREAD

**Issue by atifwaqar** [Olivine-Labs/Alchemy-Websockets#91]
Hello,
I am new to github, and i am unable to find the C# Code Examples for using Alchemy Client WebSocket. i am trying to connect a websocet to a webserver. 
Please advise.

Regards,
Atif

**Comment by ajacksified** [comment]
Hi @atifsheikh,

Check out https://github.com/Olivine-Labs/Alchemy-Websockets-Example
