### ISSUE TITLE
Client receives incomplete data

### ISSUE THREAD

**Issue by Kronos87** [Olivine-Labs/Alchemy-Websockets#96]
Hello, I got a problem with the client. When the server sends json strings in a loop without pausing the client second receive is incomplete. How does this happen? The same procedure with a dart webSocket client runs like charme and receives everything correctly. Please help.

```
    private void OnReceive(UserContext context)
    {
        String json = context.DataFrame.ToString();
        var obj = JsonConvert.DeserializeObject<MyObj>(json);
    }
```

**Comment by steforster** [comment]
I fixed this message loss, when several messages are received in the same TCP packet.
Use my [fork](https://github.com/steforster/Alchemy-Websockets) or pull request #94.

**Comment by Kronos87** [comment]
Thanks steforster. Works great. I just used your fork.Cheers.

**Comment by zyo2012** [comment]
I can confirm that steforster build is great.
One thing to remember, if your data is bigger than 100 kb it will be cut because of hard fixed variable
 public UInt64 MaxFrameSize = 102400; //100kb in Context.cs
